apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.6
  mode: ClusterWide
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    kiali:
      enabled: false
      name: kiali
    grafana:
      enabled: false
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
        ingress:
          enabled: true