apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: istio-system
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
        verbosity: detailed
      otlphttp/tempo:
        endpoint: http://dev-collector.tempo-observability.svc.cluster.local:4318
      otlphttp/jaeger:
        endpoint: http://jaeger-collector.istio-system.svc.cluster.local:4318
        tls:
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlphttp/tempo, otlphttp/jaeger]